language: generic
sudo: required
servives:
  - docker

before_install:
  - docker build -t juliomendez20/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true juliomendez20/docker-react npm run test
